FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 6520

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["GrpcService/GrpcService.csproj", "GrpcService/"]
COPY ["Backend.Configuration/Backend.Configuration.csproj", "Backend.Configuration/"]
COPY ["Client.gRPC/Client.gRPC.csproj", "Client.gRPC/"]
COPY ["Client.Configuration/Client.Configuration.csproj", "Client.Configuration/"]
COPY ["Backend.Models.DTO/Backend.Models.csproj", "Backend.Models.DTO/"]
COPY ["Backend.Implemantation/Backend.Implemantation.csproj", "Backend.Implemantation/"]
COPY ["Backend.TarantoolDB/Backend.TarantoolDB.csproj", "Backend.TarantoolDB/"]
COPY ["Backend.DBInfrastructure/Backend.DBInfrastructure.csproj", "Backend.DBInfrastructure/"]
COPY ["Backend.DI/Backend.DI.csproj", "Backend.DI/"]
COPY ["Backend.CheckDBWorkers/Backend.CheckDBWorkers.csproj", "Backend.CheckDBWorkers/"]
COPY ["Backend.SMSWorker/Backend.SMSWorker.csproj", "Backend.SMSWorker/"]
RUN dotnet restore "GrpcService/GrpcService.csproj"
COPY . .
WORKDIR "/src/GrpcService"
RUN dotnet build "GrpcService.csproj" -c Release -o /app/build

FROM build AS publish
RUN apt install libnss3-tools
RUN dotnet dev-certs https -ep GrpcService/server1.crt --format PEM
RUN certutil -d sql:$HOME/.pki/nssdb -A -t "P,," -n localhost -i GrpcService/server1.crt
RUN certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n localhost -i GrpcService/server1.crt
RUN dotnet publish "GrpcService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GrpcService.dll"]